import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { SocEmptyState, SocErrorState, SocLoadingState } from "@/components/SocFeedback";
import { SocInsightCard } from "@/components/SocInsightCard";
import { SocPageHeader } from "@/components/SocPageHeader";
import { trpc } from "@/lib/trpc";
import { LockKeyhole, ScrollText, ShieldCheck } from "lucide-react";

function AdminContent() {
  const { user } = useAuth();
  const auditQuery = trpc.soc.admin.auditLogs.useQuery(undefined, { enabled: user?.role === "admin" });
  if (user?.role !== "admin") return <div className="soc-panel mx-auto mt-16 max-w-xl p-8 text-center"><div className="mx-auto grid size-12 place-items-center rounded-xl border border-amber-300/15 bg-amber-300/5"><LockKeyhole className="size-5 text-amber-200" /></div><h1 className="mt-5 text-xl font-semibold text-slate-100">Accès administrateur requis</h1><p className="mt-3 text-sm leading-6 text-slate-400">Votre rôle Analyste donne accès aux opérations SOC. Le journal d’audit et les fonctions d’administration sont réservés aux administrateurs.</p></div>;
  return <div className="space-y-7"><SocPageHeader eyebrow="Administration" title="Journal d’audit" description="Traçabilité des opérations sensibles réalisées au sein de la plateforme. Ces données sont accessibles uniquement aux administrateurs." />
    <section className="grid gap-4 md:grid-cols-3"><SocInsightCard icon={ShieldCheck} eyebrow="Autorisation" title="Accès complet" description="Supervision des actions et paramétrage sensible." tone="safe" /><SocInsightCard icon={ScrollText} eyebrow="Preuve" title="Traçabilité" description="Créations, transitions, notifications, exports et requêtes IA." /><SocInsightCard icon={LockKeyhole} eyebrow="Contrôle" title="Contrôle serveur" description="Le rôle est validé par les procédures back-end avant la lecture." tone="warning" /></section>
    <section className="soc-panel overflow-hidden"><div className="soc-card-header border-b border-slate-800/80 px-5 py-4"><div><p className="soc-card-kicker">Audit</p><h2>Événements enregistrés</h2><p>Historique des opérations sensibles accessibles à votre rôle administrateur.</p></div><span className="soc-count-chip">{auditQuery.isLoading ? "Mise à jour…" : `${auditQuery.data?.length ?? 0} entrée${(auditQuery.data?.length ?? 0) > 1 ? "s" : ""}`}</span></div><div className="overflow-x-auto"><table className="soc-table min-w-[860px]"><thead><tr><th>Horodatage</th><th>Action</th><th>Ressource</th><th>Identifiant</th><th>Résultat</th></tr></thead><tbody>{auditQuery.isLoading ? <tr><td colSpan={5}><SocLoadingState className="px-5 py-10" label="Chargement du journal d’audit…" /></td></tr> : null}{auditQuery.isError ? <tr><td colSpan={5}><SocErrorState className="px-5 py-10" title="Journal indisponible" description={`Les opérations ne peuvent pas être chargées : ${auditQuery.error.message}`} /></td></tr> : null}{!auditQuery.isLoading && !auditQuery.isError && auditQuery.data?.length === 0 ? <tr><td colSpan={5}><SocEmptyState className="px-5 py-14" icon={ScrollText} title="Aucune action sensible n’a encore été enregistrée." description="Les transitions, exports, notifications et décisions apparaîtront ici lorsqu’elles seront réalisées." /></td></tr> : null}{auditQuery.data?.map(log => <tr key={log.id}><td className="font-mono text-xs text-slate-400">{new Date(log.createdAt).toLocaleString("fr-FR")}</td><td className="text-sm font-medium text-slate-200">{log.action}</td><td className="text-sm text-slate-300">{log.resourceType}</td><td className="font-mono text-xs text-slate-400">{log.resourceId ?? "—"}</td><td><span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-400/15 bg-emerald-400/5 px-2.5 py-1 text-xs font-medium text-emerald-200"><ShieldCheck className="size-3.5" aria-hidden="true" />Réussi</span></td></tr>)}</tbody></table></div></section></div>;
}

export default function Admin() { return <DashboardLayout><AdminContent /></DashboardLayout>; }
