import DashboardLayout from "@/components/DashboardLayout";
import { SocPageHeader } from "@/components/SocPageHeader";
import { SocChartFrame } from "@/components/SocChartFrame";
import { SeverityBadge } from "@/components/SocStatus";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { BarChart3, BrainCircuit, LineChart, Shield } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart as RechartsLineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const severityColor = { critical: "#fb7185", high: "#fb923c", medium: "#fbbf24", low: "#22d3ee" };

function AnalysisContent() {
  const dashboardQuery = trpc.soc.dashboard.useQuery();
  const alertsQuery = trpc.soc.alerts.list.useQuery();
  const categories = Object.entries((alertsQuery.data ?? []).reduce<Record<string, number>>((accumulator, { alert }) => { accumulator[alert.category] = (accumulator[alert.category] ?? 0) + 1; return accumulator; }, {})).map(([category, count]) => ({ category, count }));
  const trend = (dashboardQuery.data?.riskTrend ?? []).map(point => ({ ...point, label: new Date(point.capturedAt).toLocaleDateString("fr-FR", { day: "2-digit", month: "short" }) }));

  return <div className="space-y-7"><SocPageHeader eyebrow="Priorisation & contexte" title="Analyse des risques" description="Évolution de la posture, distribution des signaux et éléments de priorité. Les scores sont conçus pour être explicables et révisables." />
    <section className="grid gap-4 lg:grid-cols-3"><InfoCard icon={Shield} title="Score global" value={dashboardQuery.data?.metrics.globalRiskScore ?? "—"} detail="Moyenne des risques d’actifs" /><InfoCard icon={BrainCircuit} title="Signaux détectés" value={dashboardQuery.data?.metrics.activeAlerts ?? "—"} detail="Alertes qui restent à traiter" /><InfoCard icon={BarChart3} title="Incidents ouverts" value={dashboardQuery.data?.metrics.openIncidents ?? "—"} detail="Dossiers nécessitant un suivi" /></section>
    <section className="grid gap-5 2xl:grid-cols-[1.35fr_0.85fr]"><Card className="soc-panel border-slate-800 bg-slate-950/35"><CardContent className="p-5"><div className="mb-5 flex items-center gap-2"><LineChart className="h-4 w-4 text-cyan-300" /><h2 className="font-semibold text-slate-100">Évolution du risque</h2></div>{trend.length ? <SocChartFrame className="h-72"><ResponsiveContainer width="100%" height="100%"><RechartsLineChart data={trend}><CartesianGrid vertical={false} stroke="#1e293b" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#64748b", fontSize: 12 }} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} tick={{ fill: "#64748b", fontSize: 12 }} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 10 }} labelStyle={{ color: "#cbd5e1" }} /><Line type="monotone" dataKey="score" name="Score de risque" stroke="#22d3ee" strokeWidth={2.5} dot={{ r: 3, fill: "#22d3ee" }} /></RechartsLineChart></ResponsiveContainer></SocChartFrame> : <ChartEmpty label="Les instantanés de risque apparaîtront ici lorsque la plateforme commencera à recevoir des données." />}</CardContent></Card>
      <Card className="soc-panel border-slate-800 bg-slate-950/35"><CardContent className="p-5"><div className="mb-5 flex items-center gap-2"><BarChart3 className="h-4 w-4 text-cyan-300" /><h2 className="font-semibold text-slate-100">Alertes par sévérité</h2></div>{dashboardQuery.data ? <SocChartFrame className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboardQuery.data.alertsBySeverity} layout="vertical" margin={{ left: 10 }}><CartesianGrid horizontal={false} stroke="#1e293b" /><XAxis type="number" allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "#64748b", fontSize: 12 }} /><YAxis type="category" dataKey="severity" width={60} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 10 }} /><Bar dataKey="count" name="Alertes" radius={[0, 4, 4, 0]}>{dashboardQuery.data.alertsBySeverity.map(entry => <Cell key={entry.severity} fill={severityColor[entry.severity]} />)}</Bar></BarChart></ResponsiveContainer></SocChartFrame> : <ChartEmpty label="Chargement de la distribution…" />}</CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-2"><Card className="soc-panel border-slate-800 bg-slate-950/35"><CardContent className="p-5"><h2 className="font-semibold text-slate-100">Catégories de menaces</h2><div className="mt-5 space-y-3">{categories.length ? categories.map(item => <div key={item.category} className="flex items-center justify-between rounded-lg bg-slate-900/70 px-3 py-3"><span className="text-sm text-slate-300">{item.category}</span><span className="font-mono text-sm font-semibold text-cyan-200">{item.count}</span></div>) : <p className="py-12 text-center text-sm text-slate-500">Aucune catégorie n’est disponible.</p>}</div></CardContent></Card><Card className="soc-panel border-slate-800 bg-slate-950/35"><CardContent className="p-5"><h2 className="font-semibold text-slate-100">Actifs à surveiller en priorité</h2><div className="mt-5 space-y-3">{dashboardQuery.data?.highRiskAssets.length ? dashboardQuery.data.highRiskAssets.map(asset => <div className="flex items-center justify-between rounded-lg bg-slate-900/70 px-3 py-3" key={asset.id}><div><p className="text-sm font-medium text-slate-200">{asset.name}</p><p className="mt-1 text-xs text-slate-500">{asset.ipAddress ?? "Adresse inconnue"}</p></div><SeverityBadge severity={asset.riskLevel} /></div>) : <p className="py-12 text-center text-sm text-slate-500">Aucun actif élevé ou critique.</p>}</div></CardContent></Card></section></div>;
}

function InfoCard({ icon: Icon, title, value, detail }: { icon: typeof Shield; title: string; value: string | number; detail: string }) { return <Card className="soc-panel border-slate-800 bg-slate-950/35"><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-slate-400">{title}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-slate-50">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div><div className="rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-2.5"><Icon className="h-5 w-5 text-cyan-300" /></div></CardContent></Card>; }
function ChartEmpty({ label }: { label: string }) { return <div className="flex h-full items-center justify-center text-center text-sm leading-6 text-slate-500">{label}</div>; }
export default function Analysis() { return <DashboardLayout><AnalysisContent /></DashboardLayout>; }
