import DashboardLayout from "@/components/DashboardLayout";
import { SocPageHeader } from "@/components/SocPageHeader";
import { RiskMeter, SeverityBadge } from "@/components/SocStatus";
import { trpc } from "@/lib/trpc";
import { Boxes, CircleDot, ServerCog } from "lucide-react";

function AssetsContent() {
  const assetsQuery = trpc.soc.assets.list.useQuery();
  return <div className="space-y-7"><SocPageHeader eyebrow="Surface d’exposition" title="Actifs surveillés" description="Inventaire consolidé des équipements et systèmes. Les collecteurs réseau seront raccordés ultérieurement à ce référentiel." />
    <section className="soc-panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="border-b border-slate-800 bg-slate-950/40 text-[11px] uppercase tracking-[0.18em] text-slate-500"><tr><th className="px-5 py-4">Actif</th><th className="px-5 py-4">Type / plateforme</th><th className="px-5 py-4">Adresse</th><th className="px-5 py-4">Disponibilité</th><th className="px-5 py-4">Niveau</th><th className="px-5 py-4">Risque</th></tr></thead><tbody className="divide-y divide-slate-800/80">{assetsQuery.isLoading ? <tr><td colSpan={6} className="px-5 py-10 text-sm text-slate-400">Chargement de l’inventaire…</td></tr> : null}{assetsQuery.isError ? <tr><td colSpan={6} className="px-5 py-10 text-sm text-rose-300">Impossible de charger les actifs : {assetsQuery.error.message}</td></tr> : null}{assetsQuery.data?.length === 0 ? <tr><td colSpan={6}><EmptyAssets /></td></tr> : null}{assetsQuery.data?.map(asset => <tr className="transition-colors hover:bg-slate-900/50" key={asset.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="rounded-lg border border-slate-700 bg-slate-900 p-2"><ServerCog className="h-4 w-4 text-cyan-300" /></div><div><p className="font-medium text-slate-100">{asset.name}</p><p className="mt-1 text-xs text-slate-500">{asset.owner ?? "Propriétaire non défini"}</p></div></div></td><td className="px-5 py-4"><p className="text-sm capitalize text-slate-300">{asset.assetType}</p><p className="mt-1 text-xs text-slate-500">{asset.operatingSystem ?? "Plateforme inconnue"}</p></td><td className="px-5 py-4 font-mono text-sm text-slate-300">{asset.ipAddress ?? "—"}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-2 text-sm text-slate-300"><CircleDot className={`h-3.5 w-3.5 ${asset.status === "online" ? "text-emerald-400" : asset.status === "degraded" ? "text-amber-300" : "text-slate-500"}`} />{asset.status === "online" ? "En ligne" : asset.status === "degraded" ? "Dégradé" : asset.status === "offline" ? "Hors ligne" : "Inconnu"}</span></td><td className="px-5 py-4"><SeverityBadge severity={asset.riskLevel} /></td><td className="px-5 py-4"><RiskMeter value={asset.riskScore} /></td></tr>)}</tbody></table></div></section></div>;
}

function EmptyAssets() { return <div className="flex flex-col items-center gap-3 py-16 text-center"><div className="rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-3"><Boxes className="h-6 w-6 text-cyan-300" /></div><p className="font-medium text-slate-200">L’inventaire est vide.</p><p className="max-w-md text-sm text-slate-500">Les actifs ajoutés par un administrateur ou découverts sur un réseau autorisé apparaîtront ici.</p></div>; }
export default function Assets() { return <DashboardLayout><AssetsContent /></DashboardLayout>; }
