import DashboardLayout from "@/components/DashboardLayout";
import { SecurityKpiCard } from "@/components/SecurityKpiCard";
import { SocEmptyState, SocErrorState, SocLoadingState } from "@/components/SocFeedback";
import { SocPageHeader } from "@/components/SocPageHeader";
import { RiskMeter, SeverityBadge } from "@/components/SocStatus";
import { trpc } from "@/lib/trpc";
import { Boxes, CircleDot, ServerCog, ShieldAlert } from "lucide-react";

function AssetsContent() {
  const assetsQuery = trpc.soc.assets.list.useQuery();
  const assets = assetsQuery.data ?? [];
  const elevatedAssets = assets.filter(asset => asset.riskLevel === "critical" || asset.riskLevel === "high").length;
  const onlineAssets = assets.filter(asset => asset.status === "online").length;
  return <div className="space-y-7"><SocPageHeader eyebrow="Surface d’exposition" title="Actifs surveillés" description="Inventaire consolidé des équipements et systèmes. Les collecteurs réseau seront raccordés ultérieurement à ce référentiel." />
    <section className="grid gap-4 md:grid-cols-3" aria-label="Résumé de l’inventaire"><SecurityKpiCard icon={Boxes} label="Actifs inventoriés" value={assetsQuery.isLoading ? "—" : assets.length} detail="Équipements et systèmes disponibles" tone="info" /><SecurityKpiCard icon={ShieldAlert} label="Exposition élevée" value={assetsQuery.isLoading ? "—" : elevatedAssets} detail="Actifs à vérifier en priorité" tone={elevatedAssets > 0 ? "high" : "success"} /><SecurityKpiCard icon={CircleDot} label="Actifs en ligne" value={assetsQuery.isLoading ? "—" : onlineAssets} detail="Disponibilité remontée par la plateforme" tone="success" /></section>
    <section className="soc-panel overflow-hidden"><div className="soc-card-header border-b border-slate-800/80 px-5 py-4"><div><p className="soc-card-kicker">Inventaire</p><h2>Équipements et systèmes</h2><p>Adresse, disponibilité, niveau d’exposition et score de risque par actif.</p></div></div><div className="overflow-x-auto"><table className="soc-table min-w-[920px]"><thead><tr><th>Actif</th><th>Type / plateforme</th><th>Adresse</th><th>Disponibilité</th><th>Niveau</th><th>Risque</th></tr></thead><tbody>{assetsQuery.isLoading ? <tr><td colSpan={6}><SocLoadingState className="px-5 py-10" label="Chargement de l’inventaire…" /></td></tr> : null}{assetsQuery.isError ? <tr><td colSpan={6}><SocErrorState className="px-5 py-10" title="Inventaire indisponible" description={`Les actifs ne peuvent pas être chargés : ${assetsQuery.error.message}`} /></td></tr> : null}{!assetsQuery.isLoading && !assetsQuery.isError && assets.length === 0 ? <tr><td colSpan={6}><SocEmptyState className="px-5 py-14" icon={Boxes} title="L’inventaire est vide." description="Les actifs ajoutés par un administrateur ou découverts sur un réseau autorisé apparaîtront ici." /></td></tr> : null}{assets.map(asset => <tr key={asset.id}><td><div className="flex items-center gap-3"><span className="soc-row-icon"><ServerCog className="size-4" /></span><div><p className="font-medium text-slate-100">{asset.name}</p><p>{asset.owner ?? "Propriétaire non défini"}</p></div></div></td><td><p className="capitalize text-slate-300">{asset.assetType}</p><p>{asset.operatingSystem ?? "Plateforme inconnue"}</p></td><td className="font-mono text-sm text-slate-300">{asset.ipAddress ?? "—"}</td><td><span className="inline-flex items-center gap-2 text-sm text-slate-300"><CircleDot className={`size-3.5 ${asset.status === "online" ? "text-emerald-400" : asset.status === "degraded" ? "text-amber-300" : "text-slate-500"}`} aria-hidden="true" />{asset.status === "online" ? "En ligne" : asset.status === "degraded" ? "Dégradé" : asset.status === "offline" ? "Hors ligne" : "Inconnu"}</span></td><td><SeverityBadge severity={asset.riskLevel} /></td><td><RiskMeter value={asset.riskScore} /></td></tr>)}</tbody></table></div></section></div>;
}

export default function Assets() { return <DashboardLayout><AssetsContent /></DashboardLayout>; }
