import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { SecurityKpiCard } from "@/components/SecurityKpiCard";
import { SocChartFrame } from "@/components/SocChartFrame";
import { SeverityBadge } from "@/components/SocStatus";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowUpRight, BellRing, DatabaseZap, Gauge, Network, ShieldAlert } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useMemo } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const severityColors = { critical: "#fb7185", high: "#fb923c", medium: "#fbbf24", low: "#4fd1c5" };

function DashboardContent() {
  const { user } = useAuth();
  const dashboardQuery = trpc.soc.dashboard.useQuery();
  const alertsQuery = trpc.soc.alerts.list.useQuery();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const seedDemo = trpc.soc.admin.seedDemo.useMutation({ onSuccess: result => { if (result.created) toast.success("Jeu de démonstration chargé. Toutes les entrées sont explicitement étiquetées [Démo]."); else toast.info("Le jeu de démonstration ne peut être chargé que dans un inventaire vide."); void utils.soc.dashboard.invalidate(); void utils.soc.assets.invalidate(); void utils.soc.alerts.invalidate(); void utils.soc.incidents.invalidate(); }, onError: error => toast.error(error.message) });
  const metrics = dashboardQuery.data?.metrics;
  const severityDistribution = dashboardQuery.data?.alertsBySeverity ?? [];
  const recentAlerts = dashboardQuery.data?.recentAlerts ?? [];
  const coverage = metrics && metrics.monitoredSystems > 0 ? Math.round((metrics.onlineSystems / metrics.monitoredSystems) * 100) : undefined;
  const trend = (dashboardQuery.data?.riskTrend ?? []).map(point => ({ ...point, label: new Date(point.capturedAt).toLocaleDateString("fr-FR", { day: "2-digit", month: "short" }) }));
  const categories = useMemo(() => Object.entries((alertsQuery.data ?? []).reduce<Record<string, number>>((result, { alert }) => { result[alert.category] = (result[alert.category] ?? 0) + 1; return result; }, {})).map(([category, count]) => ({ category, count })), [alertsQuery.data]);

  return <div className="reference-dashboard space-y-4">
    <section className="reference-header"><div><p>DASHBOARD</p><h1>Posture de sécurité</h1><span>Vue en temps réel du périmètre SOC.{dashboardQuery.data?.isDemoData ? <em className="reference-demo-inline">Mode démonstration</em> : null}</span></div><div className="flex flex-wrap gap-2">{user?.role === "admin" && !dashboardQuery.data?.isDemoData ? <Button size="sm" variant="outline" className="reference-secondary-action" disabled={seedDemo.isPending} onClick={() => seedDemo.mutate()}><DatabaseZap className="mr-2 size-3.5" />Charger les données de démo</Button> : null}<Button size="sm" className="reference-primary-action" onClick={() => setLocation("/reports")}>Rapports sécurité <ArrowUpRight className="ml-2 size-3.5" /></Button></div></section>
    <section className="reference-kpi-grid" aria-label="Indicateurs de sécurité"><SecurityKpiCard icon={ShieldAlert} label="Menaces détectées" value={metrics?.activeAlerts ?? "—"} detail={`${metrics?.criticalAlerts ?? 0} critiques`} tone={(metrics?.criticalAlerts ?? 0) > 0 ? "critical" : "info"} /><SecurityKpiCard icon={Activity} label="Incidents actifs" value={metrics?.openIncidents ?? "—"} detail="À investiguer" tone={(metrics?.openIncidents ?? 0) > 0 ? "high" : "success"} /><SecurityKpiCard icon={Network} label="Appareils surveillés" value={metrics?.monitoredSystems ?? "—"} detail={`${metrics?.onlineSystems ?? 0} en ligne`} tone="info" progress={coverage} /><SecurityKpiCard icon={Gauge} label="Score de sécurité" value={metrics ? `${metrics.globalRiskScore}/100` : "—"} detail="Risque consolidé" tone="success" progress={metrics?.globalRiskScore} /></section>
    <section className="reference-main-grid"><article className="reference-panel reference-activity-panel"><div className="reference-panel-heading"><div><p>ACTIVITÉ DES MENACES</p><h2>{metrics ? `${metrics.globalRiskScore}/100` : "—"}</h2><span>Évolution réelle du score de risque</span></div><button className="reference-icon-action" onClick={() => setLocation("/analysis")} aria-label="Ouvrir l’analyse des risques"><ArrowUpRight className="size-4" /></button></div>{trend.length ? <SocChartFrame className="reference-main-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{ top: 12, right: 8, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke="#2a3851" strokeDasharray="3 3" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#9aa8bc", fontSize: 10 }} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} tick={{ fill: "#9aa8bc", fontSize: 10 }} /><Tooltip contentStyle={{ background: "#172338", border: "1px solid #354563", borderRadius: 2, color: "#e8eef7" }} labelStyle={{ color: "#dce6f2" }} /><Legend iconType="circle" iconSize={7} wrapperStyle={{ fontSize: 10, color: "#aab7c9" }} /><Line type="monotone" dataKey="score" name="Score de risque" stroke="#7c73ff" strokeWidth={2} dot={{ r: 3, fill: "#7c73ff" }} activeDot={{ r: 4 }} /></LineChart></ResponsiveContainer></SocChartFrame> : <p className="reference-chart-empty">Les instantanés de risque apparaîtront ici lorsque la plateforme disposera de données de tendance.</p>}</article><aside className="reference-panel reference-events-panel"><div className="reference-panel-heading"><div><p>ACTIVITÉ</p><h2>Événements récents</h2></div><button className="reference-text-action" onClick={() => setLocation("/alerts")}>Voir tout</button></div><div className="reference-events-list">{dashboardQuery.isLoading ? <p className="reference-events-empty">Chargement des événements…</p> : null}{!dashboardQuery.isLoading && recentAlerts.length === 0 ? <p className="reference-events-empty">Aucun événement de sécurité récent.</p> : null}{recentAlerts.slice(0, 5).map(alert => <button key={alert.id} className="reference-event-row" onClick={() => setLocation("/alerts")}><div><strong>EVT-{String(alert.id).padStart(4, "0")}</strong><span>{alert.title}</span><small>{new Date(alert.createdAt).toLocaleString("fr-FR", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" })}</small></div><SeverityBadge severity={alert.severity} /></button>)}</div></aside></section>
    <section className="reference-lower-grid"><article className="reference-panel reference-lower-panel"><div className="reference-panel-heading"><div><p>RÉPARTITION</p><h2>Distribution des menaces</h2></div></div>{severityDistribution.length ? <SocChartFrame className="reference-donut-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={severityDistribution} dataKey="count" nameKey="severity" cx="50%" cy="46%" innerRadius={48} outerRadius={68} paddingAngle={3}>{severityDistribution.map(entry => <Cell key={entry.severity} fill={severityColors[entry.severity]} />)}</Pie><Tooltip contentStyle={{ background: "#172338", border: "1px solid #354563", borderRadius: 2, color: "#e8eef7" }} /><Legend iconType="circle" iconSize={7} wrapperStyle={{ fontSize: 10, color: "#aab7c9" }} /></PieChart></ResponsiveContainer></SocChartFrame> : <p className="reference-chart-empty">La distribution s’affichera à partir des alertes reçues.</p>}</article><article className="reference-panel reference-lower-panel"><div className="reference-panel-heading"><div><p>CATÉGORIES</p><h2>Menaces par catégorie</h2></div></div>{categories.length ? <SocChartFrame className="reference-small-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={categories.slice(0, 6)} margin={{ top: 10, right: 0, left: -22, bottom: 0 }}><CartesianGrid vertical={false} stroke="#2a3851" /><XAxis dataKey="category" tickLine={false} axisLine={false} tick={{ fill: "#9aa8bc", fontSize: 9 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "#9aa8bc", fontSize: 9 }} /><Tooltip contentStyle={{ background: "#172338", border: "1px solid #354563", borderRadius: 2, color: "#e8eef7" }} /><Bar dataKey="count" name="Alertes" fill="#4fd1c5" radius={[1, 1, 0, 0]} /></BarChart></ResponsiveContainer></SocChartFrame> : <p className="reference-chart-empty">Les catégories apparaîtront après la réception d’alertes.</p>}</article><article className="reference-panel reference-lower-panel reference-coverage-panel"><div className="reference-panel-heading"><div><p>VISIBILITÉ</p><h2>Couverture système</h2></div></div><div className="reference-coverage-content"><div className="reference-coverage-ring" style={{ "--coverage": `${coverage ?? 0}%` } as React.CSSProperties}><strong>{coverage ?? "—"}{coverage !== undefined ? "%" : ""}</strong><span>en ligne</span></div><div className="reference-coverage-stats"><p><span>Systèmes surveillés</span><strong>{metrics?.monitoredSystems ?? "—"}</strong></p><p><span>Systèmes disponibles</span><strong>{metrics?.onlineSystems ?? "—"}</strong></p><button onClick={() => setLocation("/assets")}>Ouvrir l’inventaire <ArrowUpRight className="size-3.5" /></button></div></div></article></section>
  </div>;
}

export default function Home() { return <DashboardLayout><DashboardContent /></DashboardLayout>; }
