import DashboardLayout from "@/components/DashboardLayout";
import { asDetailedReportContent, DetailedPostureReport } from "@/components/DetailedPostureReport";
import { SocEmptyState, SocErrorState, SocLoadingState } from "@/components/SocFeedback";
import { SocInsightCard } from "@/components/SocInsightCard";
import { SocPageHeader } from "@/components/SocPageHeader";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Download, FileBarChart2, FileJson2, Printer, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

function downloadJson(filename: string, content: unknown) { const blob = new Blob([JSON.stringify(content, null, 2)], { type: "application/json;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }

function ReportsContent() {
  const reportsQuery = trpc.soc.reports.list.useQuery();
  const utils = trpc.useUtils();
  const [selectedReportId, setSelectedReportId] = useState<number | null>(null);
  const detailedReports = useMemo(() => (reportsQuery.data ?? []).filter(report => asDetailedReportContent(report.content)), [reportsQuery.data]);
  const selectedReport = detailedReports.find(report => report.id === selectedReportId) ?? detailedReports[0];
  const selectedContent = selectedReport ? asDetailedReportContent(selectedReport.content) : undefined;
  const generate = trpc.soc.reports.generatePosture.useMutation({ onSuccess: report => { toast.success("Rapport de posture détaillé généré."); setSelectedReportId(report.id); void utils.soc.reports.list.invalidate(); downloadJson(`ai-netsec-posture-detaille-${report.id}.json`, report.content); }, onError: error => toast.error(error.message) });
  return <div className="space-y-7"><div className="print:hidden"><SocPageHeader eyebrow="Gouvernance & synthèse" title="Rapports de posture" description="Générez une synthèse détaillée des risques, alertes, incidents, actifs prioritaires et recommandations. Les données sont exportables en JSON et prêtes à être imprimées en PDF." actions={<><Button className="bg-cyan-500 text-slate-950 hover:bg-cyan-300" disabled={generate.isPending} onClick={() => generate.mutate()}><Sparkles className="mr-2 size-4" />{generate.isPending ? "Génération…" : "Générer le rapport détaillé"}</Button><Button variant="outline" className="soc-secondary-button" disabled={!selectedContent} onClick={() => window.print()}><Printer className="mr-2 size-4" />Imprimer / PDF</Button></>} />
    <section className="grid gap-4 md:grid-cols-3"><SocInsightCard icon={FileBarChart2} eyebrow="Synthèse" title="Posture consolidée" description="Score global, disponibilité, signaux actifs, incidents et évolution récente." /><SocInsightCard icon={FileJson2} eyebrow="Traçabilité" title="Export structuré" description="Téléchargement JSON complet pour archivage, audit ou analyse complémentaire." /><SocInsightCard icon={Download} eyebrow="Conformité" title="Version détaillée" description="Chaque rapport conserve le périmètre, les recommandations et les limites de lecture." tone="safe" /></section>
    <section className="soc-panel overflow-hidden"><div className="soc-card-header border-b border-slate-800/80 px-5 py-4"><div><p className="soc-card-kicker">Historique</p><h2>Rapports générés</h2><p>Sélectionnez une version détaillée pour l’aperçu, l’impression ou l’export structuré.</p></div><span className="soc-count-chip">{reportsQuery.isLoading ? "Mise à jour…" : `${reportsQuery.data?.length ?? 0} disponible${(reportsQuery.data?.length ?? 0) > 1 ? "s" : ""}`}</span></div><div className="overflow-x-auto"><table className="soc-table min-w-[860px]"><thead><tr><th>Rapport</th><th>Type</th><th>Date</th><th>Actions</th></tr></thead><tbody>{reportsQuery.isLoading ? <tr><td colSpan={4}><SocLoadingState className="px-5 py-10" label="Chargement de l’historique des rapports…" /></td></tr> : null}{reportsQuery.isError ? <tr><td colSpan={4}><SocErrorState className="px-5 py-10" title="Historique indisponible" description={`Les rapports ne peuvent pas être chargés : ${reportsQuery.error.message}`} /></td></tr> : null}{!reportsQuery.isLoading && !reportsQuery.isError && reportsQuery.data?.length === 0 ? <tr><td colSpan={4}><SocEmptyState className="px-5 py-14" icon={FileBarChart2} title="Aucun rapport n’a encore été généré." description="Générez un rapport de posture détaillé pour activer l’aperçu, l’export JSON et l’impression PDF." /></td></tr> : null}{reportsQuery.data?.map(report => { const isDetailed = Boolean(asDetailedReportContent(report.content)); return <tr key={report.id} className={selectedReport?.id === report.id ? "bg-cyan-400/5" : undefined}><td><p className="font-medium text-slate-200">{report.title}</p><p className="font-mono">RPT-{String(report.id).padStart(4, "0")}</p></td><td className="text-sm capitalize text-slate-300">{isDetailed ? "Posture détaillée" : report.reportType}</td><td className="text-sm text-slate-400">{new Date(report.createdAt).toLocaleString("fr-FR")}</td><td><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" className="soc-secondary-button" onClick={() => downloadJson(`ai-netsec-${report.id}.json`, report.content)}><Download className="mr-1.5 size-3.5" />JSON</Button>{isDetailed ? <Button size="sm" variant="outline" className="border-cyan-400/30 bg-cyan-400/5 text-cyan-100 hover:bg-cyan-400/10" onClick={() => setSelectedReportId(report.id)}>Aperçu</Button> : null}</div></td></tr>; })}</tbody></table></div></section>
    {selectedReport && selectedContent ? <div className="mt-7"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Aperçu imprimable sélectionné</p><DetailedPostureReport id={selectedReport.id} title={selectedReport.title} content={selectedContent} /></div> : <SocEmptyState className="mt-7" icon={FileJson2} title="Aucun aperçu détaillé sélectionné." description="Générez un nouveau rapport détaillé pour obtenir un aperçu complet et l’impression PDF enrichie." />}</div>
    {selectedReport && selectedContent ? <DetailedPostureReport id={selectedReport.id} title={selectedReport.title} content={selectedContent} printOnly /> : null}
  </div>;
}

export default function Reports() { return <DashboardLayout><ReportsContent /></DashboardLayout>; }
